### ISSUE TITLE
error while running surgemq

### ISSUE THREAD

**Issue by goldalworming** [surgemq/surgemq#17]
hi, I test surgemq with python paho client.

I got this error log : 
E0424 18:53:12.538812   16826 process.go:55/processor] (2/testing) Error peeking next message size: EOF
E0424 18:53:44.130772   16826 sendrecv.go:55/receiver] (1/testingsub) error reading from connection: read tcp 127.0.0.1:52919: i/o timeout
E0424 18:53:44.130878   16826 process.go:55/processor] (1/testingsub) Error peeking next message size: EOF
E0424 18:54:45.138582   16826 sendrecv.go:55/receiver] (3/testingsub) error reading from connection: read tcp 127.0.0.1:36188: i/o timeout
E0424 18:54:45.139055   16826 process.go:55/processor] (3/testingsub) Error peeking next message size: EOF
E0424 18:55:32.609175   16826 process.go:55/processor] (5/testing) Error peeking next message size: EOF
E0424 18:55:35.389322   16826 sendrecv.go:55/receiver] (6/testing) error reading from connection: read tcp 127.0.0.1:37169: connection reset by peer
E0424 18:55:35.389759   16826 process.go:55/processor] (6/testing) Error peeking next message size: EOF
E0424 18:55:46.143154   16826 sendrecv.go:55/receiver] (4/testingsub) error reading from connection: read tcp 127.0.0.1:44035: i/o timeout
E0424 18:55:46.143265   16826 process.go:55/processor] (4/testingsub) Error peeking next message size: EOF
E0424 18:56:47.149011   16826 sendrecv.go:55/receiver] (7/testingsub) error reading from connection: read tcp 127.0.0.1:47237: i/o timeout
E0424 18:56:47.149102   16826 process.go:55/processor] (7/testingsub) Error peeking next message size: EOF
E0424 18:57:48.206160   16826 sendrecv.go:55/receiver] (8/testingsub) error reading from connection: read tcp 127.0.0.1:41006: i/o timeout
E0424 18:57:48.206253   16826 process.go:55/processor] (8/testingsub) Error peeking next message size: EOF
E0424 18:58:49.227415   16826 sendrecv.go:55/receiver] (9/testingsub) error reading from connection: read tcp 127.0.0.1:37368: i/o timeout
E0424 18:58:49.227507   16826 process.go:55/processor] (9/testingsub) Error peeking next message size: EOF

as you see, I got timeout that closed subscribed script connection althought mqtt has reconnect feature.
and error peeking next message while receive publish or sending subscribtion

**Comment by zhenjl** [comment]
@lufia does your PR fix this issue? Thx.

**Comment by lufia** [comment]
I think this error is fixed because I have seen same log and I'm not see the log yet.

**Comment by zhenjl** [comment]
Thanks @lufia
