### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by kpowick** [surgemq/surgemq#18]
No updates for quite some time, and the home page (http://surgemq.com) is not found.

Is this project dead?

**Comment by zhenjl** [comment]
hm...not sure why the website is dead...will fix that

however unfortunately the project is iced currently due to mainly my time availability...i am still hoping to find time to continue working on it in the near future

**Comment by zhenjl** [comment]
I fixed the website. Apparently I forgot to auto-renew the domain.
