### ISSUE TITLE
Feature Request: add support for websockets in broker

### ISSUE THREAD

**Issue by bakirov** [surgemq/surgemq#9]
Hello!

One more feature request: can you, please, add a support for websockets (standard and secure) in broker, so we can implement "MQTT over Websockets"-thing natively with SurgeMQ? Combined with [Paho's JS library](http://www.eclipse.org/paho/clients/js/) we can build very modern web applications with the benefits of MQTT.

Thanks!

**Comment by RangerMauve** [comment]
Yeah, this would be nice.

Maybe [this](https://github.com/gorilla/websocket) would be a good project to work off of for the websocket-specific stuff?

**Comment by zhenjl** [comment]
Ack. 

Thanks for the requests, and apologies for the late ack. This is definitely on my radar to add.

**Comment by jcw** [comment]
+1

**Comment by edwardchoh** [comment]
Pull request added: https://github.com/surgemq/surgemq/pull/19

**Comment by zhenjl** [comment]
@jcw @RangerMauve @bakirov Is there anyway you guys can take a look at @edwardchoh's PR and see if that works? Really appreciate all your help!

**Comment by zhenjl** [comment]
See @edwardchoh 's PR https://github.com/surgemq/surgemq/pull/19
